"""Tests for the :mod:`campy.datastructures.shuffle` module."""
# These reference shuffled values are being generated by Python running
# 3.7.2 (default, Dec 27 2018, 07:35:06) \n[Clang 10.0.0 (clang-1000.11.45.5)]
# on macOS 10.14.2

from campy.datastructures.shuffle import shuffle

import random


def test_shuffle_list():
    random.seed(41)
    assert shuffle([3, 1, 4, 1, 5, 9]) == [5, 9, 3, 1, 4, 1]


def test_shuffle_tuple():
    random.seed(41)
    assert shuffle((3, 1, 4, 1, 5, 9)) == (5, 9, 3, 1, 4, 1)


def test_shuffle_string():
    random.seed(41)
    assert shuffle('abcdefg') == 'afgebcd'


def test_shuffle_bytes():
    random.seed(41)
    assert shuffle(b'abcdefg') == b'afgebcd'


def test_shuffle_bytearray():
    random.seed(41)
    assert shuffle(bytearray(b'abcdefg')) == bytearray(b'afgebcd')


# def test_shuffle_dict():

# def test_shuffle_set():

# def test_shuffle_frozenset():

# Other types to test: namedtuple? defaultdict? counter? collections abc subclasses?

# def test_shuffle_noniterable():

